### ISSUE TITLE
[HeaderLayout] 화면 구성 및 Unit Test

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#21]
## 1. TODO

- [x]  Unit Test 작성.
- [x]  Bootstrap navbar를 이용해서 네비게이션 바 구성
- [x] 로고 설정(이미지, 라우팅)
- [x] 로그인 버튼 생성
- [x]  NavItem 컴포넌트 생성해 아이템 구성
- [x]  메뉴 리스트를 props로 넘어옴

### 2.1.  HeaderLayout
- [x] 로고 잘 출력되는가?
- [x] 로그인 버튼 잘 생성되었는가?
- [x] props로 전해준 menus에 따라 올바른 수의 NavItem들이 생성되었는가?

### 2.2. NavItem
- [x] NavItem이 props.menu에 따라 올바르게 생성되었는가?
- [x] 현재 route에 따라 active가 적용되었는가?
- [x] 등록되지 않은 route인 경우 active가 적용되지 않는가?

## 3. 유의사항
- NavItem에 전달하는 데이터는 name(String), route(String)
