### ISSUE TITLE
[NavItem] 화면 구성 및 Unit Test 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#22]
# 1. TODO

- [ ]  Unit Test 작성.
- [ ]  Bootstrap navbar를 이용해서 UI 구성
- [ ]  route, name, active 정보를 props로 
- [ ]  현재 navigate하고 있는 페이지의 번호도 props로 받아옴.

# 2. Test Case

## 2.1.  NavItem
- [ ] props로 넘어온 데이터가 출력되었는가?
- [ ] props로 active가 true로 넘어왔을 때 class가 active인 요소가 존재하는가?
- [ ] props로 active하지 않다고 하면 active가 지정되지 않았는가? (실패 Test)
- [ ] 설정에 따라 router가 정상적으로 동작하는가?

# 3. 유의사항
- vuex에 있는 메뉴 리스트 정보 받아오지 않도록 함.
- 독립적인 Unit Test 작성
