### ISSUE TITLE
[MainPage] 화면 구성 및 Unit Test

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#23]
# 1. TODO
- [x]  views아래 main 디렉터리 생성
- [x]  main 디렉터리 내부에 pages디렉터리, components 디렉터리, MainView.vue 생성
- [x] Views 디렉터리 내부에 MainPage, ConcertPage, ManagerPage, PatronPage, MapPage, FaqPage 생성(.vue)
- [x] 생성된 pages로 레이아웃 구성 
- [x] Unit Test 작성

---

# 2. Test Case
- [x] Slides들이 의도대로 화면에 잘 위치하는가?

---

# 3. 유의사항
- Components폴더는 MainPage에서만 사용하는 컴포넌트들을 넣는다. (예를 들면 회장단을 보여주는 뷰에서 반복되는 카드 컴포넌트)
- 데이터는 후에 동적으로 받아올 가능성이 있기 때문에 model에서 생성해 동적으로 넣는다.
- ShallowMount로 테스트
