### ISSUE TITLE
[main] TopPage 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#30]
# 1. TODO
- [ ] axios, vuex 이용해 API 호출
- [ ] 지원 Modal 개발
- [ ] vuex 정보 받아와서 연주회 지원 가능 여부에 따라 Modal버튼 활성화 및 버튼 캡션 설정

---

# 2. Test Case
- [ ] vuex를 mock하여 데이터 전달 setting
- [ ] 연주회 지원 가능 여부에 따라 버튼이 활성화 여부 테스트
- [ ] 연주회 지원 가능 여부에 따라 버튼 캡션 문구가 올바른지 테스트

---

# 3. 유의사항
- ShallowMount로 테스트
- API에서 받아온 state를 vuex에 저장하여 사용
