### ISSUE TITLE
[main] ConcertPage 수정

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#32]
# 1. TODO
- [ ] axios, vuex 이용해 서버와 데이터 통신
- [ ] API로부터 받아온 값으로 화면 구성
- [ ] media width > 576px일 때는 grid로 현재 상태와 동일하게 구성
- [ ] media width < 576px일 때는 flex로 각 요소가 한 줄씩 표시되도록 구성

---

# 2. Test Case
- [ ] vuex mocking setting
- [ ] API로부터 받아온 값이 올바르게 표시되는지 테스트

---

# 3. 유의사항
- CSS구성이 어려울 것으로 예상
- API가 구현되어 있지 않다면 vuex에 dummy 데이터 넣어두고 먼저 구현한 후 나중에 API 연동
