### ISSUE TITLE
[main] ManagerPage 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#33]
# 1. TODO
- [x] #44
- [x] vuex에 저장된 값으로 화면 구성
- [x] ManagerProfile 생성
- [x] ManagerPage에서 값을 꺼내고 ManagerProfile에 props로 전달

---

# 2. Test Case
- [x] vuex mocking setting
# 2.1. ManagerPage
- [x] API로부터 받아온 값에 따라 올바른 갯수(3개)의 ManagerProfie이 생성되었는지 테스트

# 2.2. ManagerProfile
- [x] props로 전달받은 값에 따라 올바르게 화면에 표시되는지 테스트

---

# 3. 유의사항
- 이미지 크기는 반응형으로 조절
- API가 구현되어 있지 않다면 vuex에 dummy 데이터 넣어두고 먼저 구현한 후 나중에 API 연동
