### ISSUE TITLE
[main] DonatePage 개발 및 테스트

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#34]
# 1. TODO
- [ ] 기획 내용에 따라 DonatePage 구성
- [ ] 버튼 선택 시 /donate로 route하도록 설정

---

# 2. Test Case
- [ ] 버튼의 route가 잘 설정되었는지 테스트

---

# 3. 유의사항
_해당사헝 없음_
