### ISSUE TITLE
[main] FAQPage 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#35]
# 1. TODO
- [x] axios로 API 호출하고 vuex에 저장하여 관리
- [x] main/components 내에 FAQCard, FAQDetail 컴포넌트 생성.
- [x] FAQComponent는 slot으로 question을 받고 클릭 시 event 발생시킴
- [x] FAQDetail은 props로 question, answer를 전달받고, 뒤로 돌아가기 링크를 누르면 event 호출

---

# 2. Test Case
## 2.1. FAQPage
- [x] 입력 데이터에 따라 올바른 개수의 FAQCard가 그려지는지 테스트
- [x] event가 발생할 때 마다 화면 설정 state(card를 보여주는지, detail을 보여주는지)값이 올바르게 설정되는지 테스트
- [x] state값에 따라 화면에 올바른 컴포넌트를 보여주는지 테스트

## 2.2. FAQCard
- [x] slot에 따라 올바른 값이 표시되는지 테스트
- [x] 눌렀을 때 event가 잘 발생하는지 테스트

## 2.3. FAQDetail
- [x] props로 넘어온 값이 잘 표시되는지 테스트
- [x] 뒤로가기 버튼을 눌렀을 때 event가 잘 발생하는지 테스트

---

# 3. 유의사항
_해당사항 없음_
