### ISSUE TITLE
[concert] ConcertView 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#37]
# 1. TODO
- [ ] axios로 vuex에 연주회 리스트 호출하여 저장해두고 사용
- [ ] ConcertView 생성 및 화면 구성
- [ ] /concert/components에 ConcertCard 생성
- [ ] for문으로 데이터에 따라 ConcertCard 배치

---

# 2. Test Case
- [ ] 데이터에 따라 올바른 개수의 ConcertCard가 생성되었는가?

---

# 3. 유의사항
- Legacy code와 notion참조하여 개발
