### ISSUE TITLE
[concert] ConcertCard 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#38]
# 1. TODO
- [ ] props로 데이터 전달받아 컴포넌트 구성
- [ ] 이미지나 제목을 클릭할 경우 /concert/{concert_id} 로 route push
- [ ] #37 에서 개발한 ConcertView에 적용

---

# 2. Test Case
- [ ] 전달받은 데이터가 화면에 잘 표시되는지 테스트
- [ ] 클릭하는 경우 올바른 route로 push되는지 테스트

---

# 3. 유의사항
- #37 가 완료된 이후 개발
