### ISSUE TITLE
[concert] ConcertDetail 개발 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#39]
# 1. TODO
- [ ] /concerts/{id} 로 router 설정
- [ ] get_api_endpoint() 메서드 작성해 axios로 호출할 url 구성
- [ ] 컴포넌트 내부에서 axios로 데이터 호출
- [ ] 화면 구성 개발

---

# 2. Test Case
- [ ] get_api_endpoint() 함수가 route의 {id}에 알맞게 url 생성하는지 테스트
- [ ] 데이터가 화면에 올바르게 표시되는지 테스트

---

# 3. 유의사항
_해당사항 없음_
