### ISSUE TITLE
[main] 기획안에 맞게 Contents 수정

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#47]
# 1. TODO
- [x] 페이지 문구 수정
- [x] 배경 사진 수정 필요 시 수정
- [x] 회장단 사진 수정
- [x] 추후 개발할 기능들 disable 설정

# 2. Test Case
- [x] Test 배포하여 팀원들 눈으로 확인

# 3. 유의사항
_해당사항 없음_
