### ISSUE TITLE
[donate] DonateView 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-web-frontend#55]
# 1. TODO
- [ ] `/views` 디렉터리에 `/donate` 디렉터리 생성
- [ ] `/donate` 내에 `DonateView` 생성
- [ ] `axios` 로 후원 목적 리스트 `GET`하여 vuex에 저장하여 select 혹은 checkbox에 적용
- [ ] `axios` 로 입력받은 폼을 서버에 `POST`

# 2. Test Case
- [ ] axios와 vuex를 mocking하여 테스트
- [ ] store에 있는 값에 따라 올바르게 화면에 적용되는지 테스트
- [ ] 사용자 입력 폼이 의도대로 `POST`되는지 테스트

# 3. 유의사항
- 없음
